site_name: KSKB-IX
theme:
  name: material
  # name: flatly
  features:
    - navigation.tabs
extra_css:
  - css/hidefooter.css
markdown_extensions:
  - pymdownx.tilde
  - pymdownx.extra
nav:
  - KSKB-IX: index.md
  - Route Server Configuration: RS.md
  - Poema Network: "https://net.kskb.eu.org"
site_url: https://ix.kskb.eu.org/
repo_url: https://github.com/KSKBpage/KSKB-IX
edit_uri: blob/main/docs/
